### ISSUE TITLE
Mudar códigos de tipo de jurisdição, tipo de órgão e qualquer outra de letras para palavras

### ISSUE THREAD

**Issue by nazareno** [dadosjusbr/api-doc#6]
Sugiro que em vez de 

 {
    "aid": "tjpb",
    "name": "Tribunal de Justiça do Estado da Paraíba",
    "type": "E",
    "entity": "J",
...
  },

tenhamos

 {
    "aid": "tjpb",
    "name": "Tribunal de Justiça do Estado da Paraíba",
    "type": "Estadual",
    "entity": "Tribunal",
...
  },

**Comment by nazareno** [comment]
Algum contra em deixar assim mais descritivo, @danielfireman ?

**Comment by danielfireman** [comment]
Você se refere a parte JSON da API ou nos pacotes de dados (zips), @nazareno ?

**Comment by nazareno** [comment]
à parte JSON

**Comment by danielfireman** [comment]
@Manuel-Antunes precisamos modificar a collection `ag` no banco de dados.

**Comment by Manuel-Antunes** [comment]
O cadastro da `ag` é feito manualmente né ?

**Comment by danielfireman** [comment]
> O cadastro da `ag` é feito manualmente né ?

Exatamente
